services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Použij Dockerfile-gradle pro Gradle projekt
    container_name: sky-app
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/skydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - JAVA_OPTS=-Xms256m -Xmx512m
    networks:
      - sky-network
    restart: no

  database:
    image: postgres:14-alpine
    container_name: sky-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=skydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sky-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  sky-network:
    driver: bridge

volumes:
  postgres-data:
